version: '3.8'

services:
  mongodb:
    image: mongo:6.0.14
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: changeme123
      MONGO_INITDB_DATABASE: rezo_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    healthcheck:
      test: |
        mongo --quiet --eval '
          db.adminCommand({
            ping: 1,
            user: "mongoadmin",
            pwd: "changeme123"
          }).ok
        ' admin || exit 1
      interval: 15s
      timeout: 30s
      retries: 6
      start_period: 60s
    ports:
      - "27017:27017"

  postgres:
    image: postgres:15.5-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme123
      POSTGRES_DB: rezo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rezo_db"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  app:
    image: your-app-image  # Replace with your actual app image
    container_name: app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MONGODB_URI: "mongodb://mongoadmin:changeme123@mongodb:27017/rezo_db?authSource=admin"
      DATABASE_URL: "postgresql://postgres:changeme123@postgres:5432/rezo_db?schema=public&connection_limit=20&pool_timeout=10"
      # Add other app environment variables here
    networks:
      - backend
    ports:
      - "3000:3000"  # Adjust port as needed

volumes:
  mongodb_data:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge